# Generated by Django 3.1.7 on 2021-03-20 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='journal',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='base',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='base',
        ),
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateField(auto_created=True, default=datetime.datetime(2021, 3, 20, 5, 25, 3, 38619)),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='journal',
            name='created_at',
            field=models.DateField(auto_created=True, default=datetime.datetime(2021, 3, 20, 5, 25, 3, 38619)),
        ),
        migrations.AddField(
            model_name='journal',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='journal',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='book',
            name='num_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='BookJournalBase',
        ),
    ]
